### ISSUE TITLE
[Setting] 프로젝트 세팅

### ISSUE THREAD

**Issue by devxsby** [SOPT-TEAM6-Aladin/Aladin-iOS#3]
## 🛠 Issue

- 프로젝트 세팅

## 📝 To-do

- [x] 폴더링
- [x] 라이브러리 추가
- [x] 탭바 세팅
- [x] 에셋 추가 (폰트, 이미지, 컬러)
- [x] 기타 세팅

**Comment by zzongha** [comment]
세팅 너무 감사합니다 ~,,~
